# Google Gemini API Configuration
# Copy this content to Streamlit Cloud Settings → Secrets

GOOGLE_API_KEY = "your-google-gemini-api-key-here"
OPERATOR_ACCESS_CODE = "BusinessDoctor2024!"
SHOW_MODE_SWITCHER = false

# Optional: Add these if you want to track usage
ENABLE_ANALYTICS = false
MAX_CONVERSATION_LENGTH = 60  # minutes