# Add your API keys here before deployment
# This file should NOT be committed to git

ANTHROPIC_API_KEY = "your-anthropic-api-key-here"
OPENAI_API_KEY = "your-openai-api-key-here"

# Development mode settings
SHOW_MODE_SWITCHER = false  # Set to true during development

# Security settings
OPERATOR_ACCESS_CODE = "BusinessDoctor2024!"  # Change this!