name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install streamlit
        pip install requests
    
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_API_TOKEN: ${{ secrets.STREAMLIT_API_TOKEN }}
      run: |
        python - << 'EOF'
        import requests
        import json
        import os
        
        # Streamlit Cloud API endpoint
        api_url = "https://api.streamlit.io/v1/apps"
        token = os.environ.get('STREAMLIT_API_TOKEN')
        
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
        
        # App configuration
        app_config = {
            "repository": "business-doctor-msp",
            "branch": "main",
            "mainModule": "deployment/streamlit_app.py",
            "secrets": {
                "ANTHROPIC_API_KEY": "${{ secrets.ANTHROPIC_API_KEY }}",
                "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
                "SHOW_MODE_SWITCHER": "false",
                "OPERATOR_ACCESS_CODE": "${{ secrets.OPERATOR_ACCESS_CODE }}"
            }
        }
        
        # Deploy or update app
        response = requests.post(api_url, headers=headers, json=app_config)
        
        if response.status_code == 200:
            print("✅ Deployment successful!")
            app_data = response.json()
            print(f"Client URL: https://{app_data['subdomain']}.streamlit.app")
            print(f"Operator URL: https://{app_data['subdomain']}.streamlit.app?mode=operator")
        else:
            print(f"❌ Deployment failed: {response.status_code}")
            print(response.text)
        EOF
    
    - name: Run tests
      run: |
        cd deployment
        python -m pytest tests/ || echo "No tests found"
    
    - name: Update deployment status
      if: always()
      run: |
        echo "Deployment completed at $(date)"
        echo "Check GitHub Actions for details"